networks:
  my_app-network:
    name: my_app_network
    driver: bridge

volumes:
  my_app_postgres_data:

services:
  postgres:
    image: postgres:17-alpine
    container_name: my_app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-my_app_production}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    networks:
      - my_app-network
    ports:
      - "5432:5432"
    volumes:
      - my_app_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-my_app_production} -h ${POSTGRES_HOST:-localhost} -p ${POSTGRES_PORT:-5432}"]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles:
      - deploy
      - server
