include:
  - ./compose.postgres.yaml

x-build-common: &build-common
  context: ../../
  # args:
  #   BUILDKIT_INLINE_CACHE: "1"
  # cache_from:
  #   - type=local,src=../.buildx-cache
  # cache_to:
  #   - type=local,dest=../.buildx-cache,mode=max

x-service-app-common: &service-app-common
  restart: unless-stopped
  environment:
    - NODE_ENV=production
  networks:
    - my_app-network

services:
  cli:
    <<: *service-app-common
    build:
      <<: *build-common
      dockerfile: docker/apps/cli.Dockerfile
    image: my_app/cli:latest
    container_name: my_app-cli
    env_file:
      - .env.production
    depends_on:
      postgres:
        condition: service_healthy

  server:
    <<: *service-app-common
    build:
      <<: *build-common
      dockerfile: docker/apps/server.Dockerfile
    image: my_app/server:latest
    container_name: my_app-server
    env_file:
      - .env.production
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-monorepo_template}}
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  web:
    <<: *service-app-common
    build:
      <<: *build-common
      dockerfile: docker/apps/web.Dockerfile
    image: my_app/web:latest
    container_name: my_app-web
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_started
